### ISSUE TITLE
missing ** in EventHandler __call__

### ISSUE THREAD

**Issue by JamesGalt** [numberoverzero/accordian#1]
on line 202:
`            task = self.loop.create_task(callback(filtered_kwargs))`

should be 
`            task = self.loop.create_task(callback(**filtered_kwargs))`

**Comment by numberoverzero** [comment]
Thanks for opening an issue, this bugs is pretty serious!

It's been a while since I've touched this code, and the asyncio module has received some significant upgrades since this library was written:

* [3.6 changes](https://docs.python.org/3/whatsnew/3.6.html#asyncio)
* [3.7 changes](https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-asyncio)
* [3.8 changes](https://docs.python.org/3/whatsnew/3.8.html#asyncio)

What do you intend or currently use `accordian` for?  I'm wondering if this library even needs to exist, given the improvements to `asyncio`.

If this still has a use then beyond addressing this issue I'd like to simplify the code with the improvements asyncio has received, both for performance and clarity.

**Comment by JamesGalt** [comment]
Hi,
Thank you for the quick answer,
I am using accordian to send connected and disconnected events from a websocket connection to handlers to fetch missing data.

I was about to write something very similar when I came across your lib which fits well my needs.

If you have any idea on how to simplify/update it for recent python versions I would be grateful if you could share them.

I am currently using python 3.8.

Again thank you very much for for your work and help.

Cheers 
James

**Comment by numberoverzero** [comment]
Thanks for the context, that helps.  I think there are two cases to consider:

* collecting results from an unknown number of receivers
* scheduling events without waiting

Here's what I'm thinking for the api, along with a sample definition of some receivers and a sender: https://gist.github.com/numberoverzero/f09e8eec841702f00464c6d249c81e65

**Comment by numberoverzero** [comment]
I need to test `*args` and `**kwargs` but the syntax looks promising.  Using the following test file:

```
import asyncio
from accordian import signal
test = signal("test")

@test.connect
async def r1():
    return 1

@test.connect
async def r2():
    return 2

@test.connect
async def r3():
    return 3

async def main():
    results = await test.join()
    assert set(results) == {1, 2, 3}
    print("done")

asyncio.run(main())
```

**Comment by JamesGalt** [comment]
Looks nice! Let me know if you want me to do some testing within my use case. Thanks

**Comment by numberoverzero** [comment]
I believe it's good to go.  Can you try out the [feature/py38-update](https://github.com/numberoverzero/accordian/tree/feature/py38-update) branch?

I'd primarily like to see what, if anything, is missing or unclear.  There are options for expansion afterwards, such as allowing a `Signal` to override task creation (eg. validation, chaining, other pre-processing).

**Comment by JamesGalt** [comment]
looks good, I'll implement it tomorrow and will send you a feedback.
Thank you very much :)

**Comment by numberoverzero** [comment]
Any chance to test this out yet?  I'd like to release to pypi if the api is comfortable.

**Comment by JamesGalt** [comment]
Sorry for the delay, I have been busier than I initially thought.
Absolutely brilliant! thanks a lot. I really like how neat the code is. I wouldn't change a single line of it.

**Comment by numberoverzero** [comment]
0.4.0 released.  Thanks so much for the feedback!
